// Package main regenerates the committed canary model.
package main

import (
	"fmt"
	"io"
	"os"
)

const generatedModel = `// Code generated by go generate; DO NOT EDIT.

// Package generated is committed output used to test generated-source handling.
package generated

// Model identifies the schema exercised by this fixture.
const Model = "schema-2"
`

func main() {
	os.Exit(run("generated/model.go", os.Stderr))
}

func run(path string, stderr io.Writer) int {
	if err := os.WriteFile(path, []byte(generatedModel), 0o600); err != nil {
		_, _ = fmt.Fprintln(stderr, err)
		return 1
	}
	return 0
}
